name: movie_ticket
description: Proyek UAS Pemrograman Multi-Platform

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.1.1
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
