name: movie_ticket
description: Proyek UAS Pemrograman Multi-Platform

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/
